apiVersion: v1
kind: Service
metadata:
  name: spark-appname-1-svc
  namespace: dev
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Pod
    name: spark-appname-1
    uid: 98a7531c-c028-11e9-adb1-00163e20c49c
  selfLink: /api/v1/namespaces/dev/services/spark-appname-1-svc
spec:
  clusterIP: None
  ports:
  - name: driver-rpc-port
    port: 7078
    protocol: TCP
    targetPort: 7078
  - name: blockmanager
    port: 7079
    protocol: TCP
    targetPort: 7079
  selector:
    spark-app-selector: spark-appid-1
    spark-role: driver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
