apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-08-16T08:30:24Z
  name: spark-new-1565944221737-driver-svc
  namespace: dev
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Pod
    name: spark-new-1565944221737-driver
    uid: 17526233-c000-11e9-adb1-00163e20c49c
  resourceVersion: "9371553"
  selfLink: /api/v1/namespaces/dev/services/spark-new-1565944221737-driver-svc
  uid: 17a60aad-c000-11e9-adb1-00163e20c49c
spec:
  clusterIP: None
  ports:
  - name: driver-rpc-port
    port: 7078
    protocol: TCP
    targetPort: 7078
  - name: blockmanager
    port: 7079
    protocol: TCP
    targetPort: 7079
  selector:
    spark-app-selector: spark-122edf4ab1aa4cba8cc3fd2877f1218e
    spark-role: driver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
